### ISSUE TITLE
SDK version v5.15.1.17995 support

### ISSUE THREAD

**Issue by DK013** [tanchunsiong/raw-data-access-on-zoom-meeting-sdk-for-windows-custom-ui#2]
As it seems the latest SDK version v5.15.1.17995 has changed the structure a little. Can we please have a branch for latest SDK support? 

It will be really helpful
Thanks

**Comment by tanchunsiong** [comment]
updated to support 5.15.2

**Comment by tanchunsiong** [comment]
updated to support 5.15.2
